# Painless development and deployment with Docker.
# Visit the docs at https://docs.docker.com/compose/
# Codeship specific docs: https://documentation.codeship.com/docker/services/

version: '2'
services:
  app:
    image: frolvlad/alpine-python3
