# Painless deployment with GitLab CI.
# Visit the docs at https://docs.gitlab.com/ce/ci/

image: python:3.5

test:
  before_script: pip install tox
  script: tox

staging:
  type: deploy
  script:
  - echo 'This build would deploy to Staging now.'
  only:
  - master

production:
  type: deploy
  script:
  - echo 'This build would deploy to Production now.'
  only:
  - tags
