# Painless deployment with GitLab CI.
# Visit the docs at https://docs.gitlab.com/ce/ci/

test:
  script: tox

staging:
  type: deploy
  script:
  - ### DEPLOYMENT STEPS STAGING ###
  only:
  - master

production:
  type: deploy
  script:
  - ### DEPLOYMENT STEPS PRODUCTION ###
  only:
  - tags
