# Painless deployment with GitLab CI.
# Visit the docs at https://docs.gitlab.com/ce/ci/

test:
  script: tox

staging:
  type: deploy
  script:
  - echo 'This build would deploy to Staging now.'
  only:
  - master

production:
  type: deploy
  script:
  - echo 'This build would deploy to Production now.'
  only:
  - tags
