# Painless deployment with GitLab CI.
# Visit the docs at https://docs.gitlab.com/ce/ci/

image: painless/tox:multi

stages:
- check
- test
- build
- deploy
{% for env in cookiecutter.checks.split(",") %}
{{ env }}:
  stage: check
  script: tox -e {{ env }}
{% endfor %}
{%- for env in cookiecutter.tests.split(",") %}
{{ env }}:
  stage: test
  script: tox -e {{ env }}
{% endfor %}
build:
  stage: build
  script:
  - echo 'This build would build a Docker image and push it to the registry.'
  only:
  - feature/*

staging:
  stage: deploy
  script:
  - echo 'This build would deploy to Staging now.'
  only:
  - master

production:
  stage: deploy
  script:
  - echo 'This build would deploy to Production now.'
  only:
  - tags
