# Painless deployment with Travis CI.
# Visit the docs at https://docs.travis-ci.com/

sudo: false
language: python
python: 3.5

env:
  matrix:  # $ tox -l | sort | xargs -I ARG echo '  - TOXENV=ARG'
    - TOXENV=flake8
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy

install:
  - pip install tox
script: tox

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
