apiVersion: v1
kind: Route
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  name: application
  labels:
    app: {{ cookiecutter.project_slug }}
    component: application
spec:
  port:
    targetPort: web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: application
