apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: {{ cookiecutter.project_slug }}
    component: application
spec:
  ports:
  - name: web
    port: 80
    targetPort: nginx
  selector:
    app: {{ cookiecutter.project_slug }}
    component: application
  type: ClusterIP
